### ISSUE TITLE
Can't build ffi for discrete heat equation.

### ISSUE THREAD

**Issue by jxxcarlson** [pepijndevos/futhark-pycffi#8]
I'm getting this error after doing `futhark pyopencl --library heat.fut`:

```
$ build_futhark_ffi heat
Traceback (most recent call last):
  File "/Applications/anaconda/bin/build_futhark_ffi", line 10, in <module>
    sys.exit(main())
  File "/Applications/anaconda/lib/python2.7/site-packages/futhark_ffi/build.py", line 22, in main
    ffi = build(name)
  File "/Applications/anaconda/lib/python2.7/site-packages/futhark_ffi/build.py", line 14, in build
    with open(name+'.h') as header:
IOError: [Errno 2] No such file or directory: 'heat.h'
```

**Comment by athas** [comment]
futhark-pycffi uses the C/OpenCL backend, so you'll have to run `futhark opencl --library heat.fut`.  Beyond that, it might also have bitrotted a bit - I certainly have not used it in a while.

**Comment by jxxcarlson** [comment]
Yes, there must be some bit-rot :-)

```
 $ futhark opencl --library heat.fut
 $ build_futhark_ffi heat
Traceback (most recent call last):
  File "/Applications/anaconda/bin/build_futhark_ffi", line 10, in <module>
    sys.exit(main())
  File "/Applications/anaconda/lib/python2.7/site-packages/futhark_ffi/build.py", line 22, in main
    ffi = build(name)
  File "/Applications/anaconda/lib/python2.7/site-packages/futhark_ffi/build.py", line 16, in build
    ffibuilder.cdef(cdef)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/api.py", line 106, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/api.py", line 120, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/cparser.py", line 308, in parse
    self._internal_parse(csource)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/cparser.py", line 313, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/cparser.py", line 271, in _parse
    self.convert_pycparser_error(e, csource)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/cparser.py", line 300, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "cl_command_queue queue);"
:107:41: before: cl_command_queue
```

**Comment by jxxcarlson** [comment]
Here is `heat.fut`: https://gist.github.com/jxxcarlson/78f9d7d61a628ab229155503a263bedb (my first Futhark program)

**Comment by athas** [comment]
Did you install futhark-pycffi from Git?  I think I fixed your issue [here](https://github.com/pepijndevos/futhark-pycffi/pull/7), but I don't think a new version has been pushed to pypi since.

**Comment by athas** [comment]
For your command line test, I'm not surprised it doesn't work.  Futhark command line programs accept only their own bespoke input format (you can generate it with [futhark-dataset](https://futhark.readthedocs.io/en/latest/man/futhark-dataset.html)), because they are not really supposed to be used for anything but testing.  I am however a bit surprised that you don't get an error message.

**Comment by pepijndevos** [comment]
Ah, I this is indeed the issue, I should probably do a pypi release.
Is that command queue business already in a stable futhark release?
I think it makes sense to use git futhark with git pycffi and released futhark with released pycffi.

**Comment by athas** [comment]
Yes, the current Git futhark-pycffi works with both released and Git Futhark (and will for quite a while; the API is generally pretty stable).

**Comment by pepijndevos** [comment]
I've tested your code by running

```
futhark opencl --library  heat.fut
build_futhark_ffi heat
python test.py
```

with the following test program:

```
import numpy as np
import _heat
from futhark_ffi import Futhark

data = np.zeros([3,3])
data[1,1] = 1

test = Futhark(_heat)
res = test.main(1, 0.5, data)
print(test.from_futhark(res))
```

I've released the new code on pypi, which shouls solve your issue. If no, feel free to reopen.

**Comment by jxxcarlson** [comment]
Below is another try.  Encouraging, but the types 
are wrong.  What should I be doing?

**Python program**

```
# File: heatDemo.py
import numpy as np
import heat

np.random.seed(0)                              # seed for reproducibility
x2 = np.random.uniform(0,0.1,25).reshape(5,5)  # 2D array of low-level noise
x2[2,2] = 1.0                                  # hot spot

heat.heat.main(heat.heat(),1, 0.5, x2)
```

**Result**

```
 $ python heatDemo.py
/Applications/anaconda/lib/python2.7/site-packages/pyopencl/__init__.py:235: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
Traceback (most recent call last):
  File "heatDemo.py", line 8, in <module>
    heat.heat.main(heat.heat(),1, 0.5, x2)
  File "/Users/carlson/dev/futhark/heat/heat.py", line 2354, in main
    field_mem_4750_ext))
TypeError: Argument #2 has invalid value
Futhark type: [][]f32
Argument has Python type <type 'numpy.ndarray'> and value: [[ 0.05488135  0.07151894  0.06027634  0.05448832  0.04236548]
 [ 0.06458941  0.04375872  0.0891773   0.09636628  0.03834415]
 [ 0.0791725   0.05288949  1.          0.09255966  0.00710361]
 [ 0.00871293  0.00202184  0.08326198  0.07781568  0.08700121]
 [ 0.09786183  0.07991586  0.04614794  0.07805292  0.01182744]]
```

**Comment by jxxcarlson** [comment]
@pepijndevos Thank you so much for your help (and for `test.py`).  I'm still having a problem, but I am pretty sure it is with the opencl setup on mac os.  I installed `build_futhark_ffi` directly from your repo: `git clone`, then `python setup.py install`. When I run `build_futhark_ffi heat`, I get a long list of warnings, then the message below:

```
229 warnings generated.
ld: library not found for -lOpenCL
((ETC))
```

Any advice on this?  I wasn't able yet to find helpful info via Google.

**Comment by athas** [comment]
macOS needs `-framework OpenCL` as a C compiler command line option.  The Futhark compiler does this automatically when it detects it is running on macOS.  I guess futhark-pycffi should do the same somehow.  I guess it can be done by extending/modifying [these lines](https://github.com/pepijndevos/futhark-pycffi/blob/master/futhark_ffi/build.py#L10-L13), but I don't have a Mac at hand to test it.

**Comment by jxxcarlson** [comment]
I will see if I can hack the code to do this.  Thanks!

**Comment by pepijndevos** [comment]
FYI, you can test if the Python side of things works by using `futhark c` instead.

I'd be happy to accept a pull request if you can make the code indicated by @athas select the right flags on MacOS.

**Comment by jxxcarlson** [comment]
Considerable progress, but still not quite there.
I made the following change in `build.py`:

```
    with open(name+'.c') as source:
        ffibuilder.set_source('_'+name, source.read(), libraries=[],
                             extra_compile_args=["-std=c99",  "-ld -framework OpenCL"])
```
After running `python setup.py install`, I get this:

```
$ build_futhark_ffi heat
clang: warning: -ld -framework OpenCL: 'linker' input unused [-Wunused-command-line-argument]
(((Warnings)))
229 warnings generated.
$
```
which is good.  However, the next step fails:

```
 $ python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import _heat.o
ImportError: dlopen(/Users/carlson/dev/futhark/heat/_heat.so, 2): Symbol not found: _clBuildProgram
  Referenced from: /Users/carlson/dev/futhark/heat/_heat.so
  Expected in: flat namespace
 in /Users/carlson/dev/futhark/heat/_heat.so
```

**Comment by athas** [comment]
Don't put `-ld -framework OpenCL`; it's just `-framework OpenCL` (you may has to pass it as two separate `extra_compile_args` - I don't know cffi well enough.

You might encounter another issue even if you get that working: most Macs have multiple OpenCL devices.  For example, my Macbook has a CPU, Intel GPU, and AMD GPU (provided to OpenCL in that order).  The CPU OpenCL driver is quite defective and already blacklisted by Futhark, but unless otherwise specified, Futhark will use the Intel GPU, which may not be what you want.  Futhark provides knobs for selecting a different device, but I don't think they are exposed by futhark-pycffi.

**Comment by jxxcarlson** [comment]
I changed things from
```
extra_compile_args=["-std=c99",  "-ld -framework OpenCL"])
```
to
```
extra_compile_args=["-std=c99",  "-framework OpenCL"])
```

But then there is a compile error:

```
 $ build_futhark_ffi heat
clang: error: unknown argument: '-framework OpenCL'
Traceback (most recent call last):
  File "/Applications/anaconda/bin/build_futhark_ffi", line 11, in <module>
    load_entry_point('futhark-ffi==0.10.2', 'console_scripts', 'build_futhark_ffi')()
  File "build/bdist.macosx-10.7-x86_64/egg/futhark_ffi/build.py", line 26, in main
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Applications/anaconda/lib/python2.7/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by athas** [comment]
Try `extra_compile_args=["-std=c99",  "-framework", "OpenCL"])`.

**Comment by jxxcarlson** [comment]
Tried that -- symbol still not found:

```
 $ python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import _heat.o
ImportError: dlopen(/Users/carlson/dev/futhark/heat/_heat.so, 2): Symbol not found: _clBuildProgram
  Referenced from: /Users/carlson/dev/futhark/heat/_heat.so
  Expected in: flat namespace
 in /Users/carlson/dev/futhark/heat/_heat.so
```

**Comment by athas** [comment]
This definition of `build` works for me on macOS:

```

def build(name):
    ffibuilder = FFI()

    with open(name+'.c') as source:
        ffibuilder.set_source('_'+name, source.read(), libraries=[],
                              extra_compile_args=["-std=c99", "-framework", "OpenCL"])

    with open(name+'.h') as header:
        cdef = 'typedef void* cl_command_queue;'
        cdef += '\ntypedef void* cl_mem;'
        cdef += strip_includes(header)
        cdef += "\nvoid free(void *ptr);"
        ffibuilder.cdef(cdef)

    return ffibuilder
```

Did you remember to run `build_futhark_ffi` again?

**Comment by jxxcarlson** [comment]
I'm sorry that this is so frustrating & taking so much of your time.  Here is the sequence of actions I performed.

1. Substitute your definition above of the `build` function in `futhark_ffi/build.py`

2. Run `python setup.py install`  The final message was
```
Using /Applications/anaconda/lib/python2.7/site-packages
Finished processing dependencies for futhark-ffi==0.10.2
```

3. Run `futhark opencl --library  heat.fut`, then `build_futhark_ffi heat`

4. Using

```
# File: test.py
import numpy as np
import _heat.o
from futhark_ffi import Futhark

data = np.zeros([3,3])
data[1,1] = 1

test = Futhark(_heat)
res = test.main(1, 0.5, data)
print(test.from_futhark(res))
```

do `python test.py`

The output is

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import _heat.o
ImportError: dlopen(/Users/carlson/dev/futhark/heat/_heat.so, 2): Symbol not found: _clBuildProgram
  Referenced from: /Users/carlson/dev/futhark/heat/_heat.so
  Expected in: flat namespace
 in /Users/carlson/dev/futhark/heat/_heat.so
```

**Comment by jxxcarlson** [comment]
Could the error be coming from `heat.fut`?  Here it is without comments:

```
let newValue [rows][cols]
             (beta: f32) (field: [rows][cols]f32) (row: i32) (col: i32): f32 =
   unsafe
  let sum =
      field[row-1,col] + field[row+1,col]
    + field[row,  col-1] + field[row,  col+1]
  in (1-beta) * field[row,col] + beta * (sum / 4f32)

let newField [rows][cols]
                (beta: f32) (field: [rows][cols]f32): [rows][cols]f32 =
  unsafe
  map (\row ->
        map(\col ->
              if row > 0 && row < rows-1 && col > 0 && col < cols-1
              then newValue beta field row col
              else field[row,col])
            (0...cols-1))
      (0...rows-1)

let main [rows][cols]
         (iterations: i32) (beta: f32) (field: [rows][cols]f32): [rows][cols]f32 =
  let field = loop field for _i < iterations do newField beta field
  in field

**Comment by pepijndevos** [comment]
I don't think the problem is with `heat.fut`, the error indicates a missing OpenCL symbol, so compilation is fine. It's linking that seems to be the problem. I'm not familiar with this framework business on macOS, but maybe you could play with some `LD_*` env variables to help Python find OpenCL.

**Comment by pepijndevos** [comment]
```
import _heat.o # WHAT IS THE O DOING THERE???
```
The correct version is just 

```
import _heat
```
Maybe a really silly thing to try: Import PyOpenCL *before* _heat, which must obviously load the OpenCL symbols.

**Comment by jxxcarlson** [comment]
Little note: I was able to do what I wanted using the `pyopencl` option: https://github.com/jxxcarlson/heat-futhark

Futhark is truly awesome

**Comment by athas** [comment]
Cool!  The PyOpenCL backend works well, but it is a little slower for some programs than the C+OpenCL backend used by futhark-cffi.  If you're interested in using Futhark as a backend for a web API, you may also be interested in [Futhark with Fangs](https://github.com/diku-dk/futhark-with-fangs) that I made mostly as a joke.  It's not super practical, because it is fully stateless and all data is transferred in text format, but I've always wondered whether something more polished could be built.

**Comment by jxxcarlson** [comment]
Hi @pepijndevos , your suggestion `import pyopencl` (note case) worked to suppress the missing symbol error, but revealed another:

```
 $ python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    res = test.main(1, 0.5, data)
  File "/Applications/anaconda/lib/python2.7/site-packages/futhark_ffi/__init__.py", line 121, in wrapper
    in_args = [f(a) for f, a in zip(converters, args)]
  File "/Applications/anaconda/lib/python2.7/site-packages/futhark_ffi/__init__.py", line 71, in to_futhark
    datat = data.astype(np_types[fut_type.itemtype.item.cname], copy=False, order='C')
KeyError: 'void'
```
I did run `build_futhark_ffi heat` before, just to be sure. 

Here is the version of `test.py` that I am using:

```
import numpy as np
import pyopencl
import _heat
from futhark_ffi import Futhark

data = np.zeros([3,3])
data[1,1] = 1

test = Futhark(_heat)
res = test.main(1, 0.5, data)
print(test.from_futhark(res))
```

**Comment by jxxcarlson** [comment]
PS. The code below works fine.  I tested it on a 1000x1000 array.
The response is under one eye-blink: essentially instantaneous.

```
# import heat.py, run `futhark pyopencl --library heat.fut` 
# to produce `heat.py
import heat 
heatKernel = heat.heat()

n = 6 # I'v tried n = 1000; works fine
data = np.zeros(n*n).reshape(n,n)
data[3,3]=1; data[0,1]=0.5; data[0,2]=0.5
array = np.array(data, dtype=np.float32)

class Data():
  def __init__(self):
        self.state = array

  def step(self):
        self.state = heatKernel.main(1, 0.5, self.state)
        print len(self.state), len(self.state[0])
        print self.state
        print type(self.state)

myData = Data()
```
Now use GET to the server to send the temperature 
map and update it using `step`: 

```
    def do_GET(self):
        self._set_headers()
        self.wfile.write(myData.state)
        myData.step()
```

**Comment by jxxcarlson** [comment]
PPS.  Is there a way to turn a <class 'pyopencl.array.Array'> into a byte sequence? Like what one can do using `tobytes()` for a numpy array.

**Comment by jxxcarlson** [comment]
@athas Thanks for the Futhark with Fangs ref.  I'll check it out.

**Comment by athas** [comment]
> PPS. Is there a way to turn a <class 'pyopencl.array.Array'> into a byte sequence? Like what one can do using `tobytes()` for a numpy array.

You can always check the PyOpenCL documentation for more, but there is a `.get()` method on the PyOpenCL array that will give you back a normal Numpy array, on which you can then call `.tobytes()` or whatever else you want.  Note that `.get()` is relatively expensive because it copies from the GPU to CPU.

**Comment by athas** [comment]
Did we ever resolve this one?  I cannot reproduce on my macOS.  I see you are using Anaconda - while I know of several people who've used the PyOpenCL backend with Anaconda, I don't know if anyone has tried `futhark-pycffi`, or whether special considerations need to be made.

**Comment by pepijndevos** [comment]
The KeyError seems very strange. I also cannot reproduce it. It would be useful if you could put a breakpoint on the error it and figure out what your args are and what `fut_type` is.

**Comment by lalaithion** [comment]
The fixes in the thread above work for me. I would recommend releasing a new version of the code that incorporates them (or at least point to this thread in the README).

**Comment by pepijndevos** [comment]
Which fixes did you apply exactly? Please make a PR with the ones that actually work on Mac. Too many were suggested for me to just blindly release something.

On November 13, 2019 2:38:34 AM GMT+01:00, Izaak Weiss <notifications@github.com> wrote:
>The fixes in the thread above work for me. I would recommend releasing
>a new version of the code that incorporates them (or at least point to
>this thread in the README).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pepijndevos/futhark-pycffi/issues/8#issuecomment-553197453

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by athas** [comment]
This issue is old and `futhark-pycffi` has changed a lot, so I'm closing it.
